/*
 * Message.h
 *
 * Created: 9/15/2013 1:42:42 PM
 *  Author: HP User
 */ 


#ifndef MESSAGE_H_
#define MESSAGE_H_


#include "commonheader.h"

using namespace helicopter::util::common;

/**
 * This file represents the telemetry messages going from the flight computer to the ground station. These
 * are generated by the flight computer.
 */
namespace helicopter
{
	
	namespace messages
	{
		class Message
		{
			protected:
				byte msgType;
				
				int msgSize;
				
			public:
			
				Message (byte msgType, int msgSize):
					msgType(msgType), msgSize(msgSize)
				{
					
				}
				
				virtual ~Message()
				{
					
				}
			
				byte getType()
				{
					return msgType;
				}
			
				int getMessageSize()
				{
					return msgSize;
				}
			
				virtual byte *getBytes()
				{
					return NULL;
				}
			
				virtual void buildMessage(byte *message)
				{
					//noop. subclass should implement this.
				}
		};
	}
}



#endif /* MESSAGE_H_ */