/*
 * SynchMessage.h
 *
 * Created: 9/15/2013 1:43:41 PM
 *  Author: HP User
 */ 


#ifndef SYNCMESSAGE_H_
#define SYNCMESSAGE_H_

#include "Message.h"
#include "commonheader.h"

using namespace helicopter::util::common;

/**
 * This file represents the telemetry messages going from the flight computer to the ground station. These
 * are generated by the flight computer.
 */
namespace helicopter
{
	
	namespace messages
	{
		class SyncMessage : public Message
		{
			public: 
				static const byte MessageType = 3;
							
				static const byte MessageSize =
					sizeof(msgType);
							
				SyncMessage(): Message(MessageType,MessageSize)
				{
								
				}
				//Implement virtual distructor.
				
				~SyncMessage()
				{
					
				}
			
				byte *getBytes();
			
				void buildMessage(byte *message);
			
				//Static method which creates a message on the heap
				//and then calls buildMessage on that created object.
				static SyncMessage* buildMessageSt(byte *message);
		};
	}
}




#endif /* SYNCMESSAGE_H_ */