/*
 * SystemTelemetryMessage.h
 *
 * Created: 9/8/2013 7:19:19 PM
 *  Author: HP User
 */ 


#ifndef SYSTEMTELEMETRYMESSAGE_H_
#define SYSTEMTELEMETRYMESSAGE_H_

#include "commonheader.h"

using namespace helicopter::util::common;

/**
 * This file represents the telemetry messages going from the flight computer to the ground station. These
 * are generated by the flight computer.
 */
namespace helicopter
{
	
	namespace messages
	{
		class SystemTelemetryMessage
		{
			private:
				int magX;

				int magY;

				int magZ;
				
				byte msgType;
			
			public:
				static const byte SystemTelemetryMessageType = 2;
			
				static const byte MessageSize =
				sizeof(msgType) +
				sizeof(magX) +
				sizeof(magY) +
				sizeof(magZ);
			
				SystemTelemetryMessage():
					magX(0),
					magY(0),
					magZ(0),
					msgType(SystemTelemetryMessageType)
				{
				
				}
			
				~SystemTelemetryMessage() {}
					
				byte getType()
				{
					return msgType;
				}
				
				int getMessageSize()
				{
					return MessageSize;
				}
			
				byte *getBytes();
			
				void buildMessage(byte *message);
			
				int MagX() const { return magX; }
				void MagX(int val) { magX = val; }
			
				int MagY() const { return magY; }
				void MagY(int val) { magY = val; }
			
				int MagZ() const { return magZ; }
				void MagZ(int val) { magZ = val; }
					
				//Static method which creates a telemetry message on the heap
				//and then calls buildMessage on that created object.
				static SystemTelemetryMessage* buildMessageSt(byte *message);
		};
	}
}


#endif /* SYSTEMTELEMETRYMESSAGE_H_ */